"""autogenerated by genmsg_py from PoseData.msg. Do not edit."""
import roslib.message
import struct


class PoseData(roslib.message.Message):
  _md5sum = "b0bc174e6016dc1293495107c6428485"
  _type = "cse_kinect/PoseData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool mStop
bool mGo
bool mTooClose
bool mTooFar
bool mTooClockwise
bool mTooCClockwise

"""
  __slots__ = ['mStop','mGo','mTooClose','mTooFar','mTooClockwise','mTooCClockwise']
  _slot_types = ['bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       mStop,mGo,mTooClose,mTooFar,mTooClockwise,mTooCClockwise
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(PoseData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.mStop is None:
        self.mStop = False
      if self.mGo is None:
        self.mGo = False
      if self.mTooClose is None:
        self.mTooClose = False
      if self.mTooFar is None:
        self.mTooFar = False
      if self.mTooClockwise is None:
        self.mTooClockwise = False
      if self.mTooCClockwise is None:
        self.mTooCClockwise = False
    else:
      self.mStop = False
      self.mGo = False
      self.mTooClose = False
      self.mTooFar = False
      self.mTooClockwise = False
      self.mTooCClockwise = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_6B.pack(_x.mStop, _x.mGo, _x.mTooClose, _x.mTooFar, _x.mTooClockwise, _x.mTooCClockwise))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.mStop, _x.mGo, _x.mTooClose, _x.mTooFar, _x.mTooClockwise, _x.mTooCClockwise,) = _struct_6B.unpack(str[start:end])
      self.mStop = bool(self.mStop)
      self.mGo = bool(self.mGo)
      self.mTooClose = bool(self.mTooClose)
      self.mTooFar = bool(self.mTooFar)
      self.mTooClockwise = bool(self.mTooClockwise)
      self.mTooCClockwise = bool(self.mTooCClockwise)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_6B.pack(_x.mStop, _x.mGo, _x.mTooClose, _x.mTooFar, _x.mTooClockwise, _x.mTooCClockwise))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.mStop, _x.mGo, _x.mTooClose, _x.mTooFar, _x.mTooClockwise, _x.mTooCClockwise,) = _struct_6B.unpack(str[start:end])
      self.mStop = bool(self.mStop)
      self.mGo = bool(self.mGo)
      self.mTooClose = bool(self.mTooClose)
      self.mTooFar = bool(self.mTooFar)
      self.mTooClockwise = bool(self.mTooClockwise)
      self.mTooCClockwise = bool(self.mTooCClockwise)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_6B = struct.Struct("<6B")
