/* Auto-generated by genmsg_cpp for file /home/myhelperbot/myHelperBot/rosws/cse_kinect/msg/PoseData.msg */
#ifndef CSE_KINECT_MESSAGE_POSEDATA_H
#define CSE_KINECT_MESSAGE_POSEDATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace cse_kinect
{
template <class ContainerAllocator>
struct PoseData_ {
  typedef PoseData_<ContainerAllocator> Type;

  PoseData_()
  : mStop(false)
  , mGo(false)
  , mTooClose(false)
  , mTooFar(false)
  , mTooClockwise(false)
  , mTooCClockwise(false)
  {
  }

  PoseData_(const ContainerAllocator& _alloc)
  : mStop(false)
  , mGo(false)
  , mTooClose(false)
  , mTooFar(false)
  , mTooClockwise(false)
  , mTooCClockwise(false)
  {
  }

  typedef uint8_t _mStop_type;
  uint8_t mStop;

  typedef uint8_t _mGo_type;
  uint8_t mGo;

  typedef uint8_t _mTooClose_type;
  uint8_t mTooClose;

  typedef uint8_t _mTooFar_type;
  uint8_t mTooFar;

  typedef uint8_t _mTooClockwise_type;
  uint8_t mTooClockwise;

  typedef uint8_t _mTooCClockwise_type;
  uint8_t mTooCClockwise;


private:
  static const char* __s_getDataType_() { return "cse_kinect/PoseData"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "b0bc174e6016dc1293495107c6428485"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool mStop\n\
bool mGo\n\
bool mTooClose\n\
bool mTooFar\n\
bool mTooClockwise\n\
bool mTooCClockwise\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, mStop);
    ros::serialization::serialize(stream, mGo);
    ros::serialization::serialize(stream, mTooClose);
    ros::serialization::serialize(stream, mTooFar);
    ros::serialization::serialize(stream, mTooClockwise);
    ros::serialization::serialize(stream, mTooCClockwise);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, mStop);
    ros::serialization::deserialize(stream, mGo);
    ros::serialization::deserialize(stream, mTooClose);
    ros::serialization::deserialize(stream, mTooFar);
    ros::serialization::deserialize(stream, mTooClockwise);
    ros::serialization::deserialize(stream, mTooCClockwise);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(mStop);
    size += ros::serialization::serializationLength(mGo);
    size += ros::serialization::serializationLength(mTooClose);
    size += ros::serialization::serializationLength(mTooFar);
    size += ros::serialization::serializationLength(mTooClockwise);
    size += ros::serialization::serializationLength(mTooCClockwise);
    return size;
  }

  typedef boost::shared_ptr< ::cse_kinect::PoseData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cse_kinect::PoseData_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PoseData
typedef  ::cse_kinect::PoseData_<std::allocator<void> > PoseData;

typedef boost::shared_ptr< ::cse_kinect::PoseData> PoseDataPtr;
typedef boost::shared_ptr< ::cse_kinect::PoseData const> PoseDataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cse_kinect::PoseData_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cse_kinect::PoseData_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cse_kinect

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cse_kinect::PoseData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cse_kinect::PoseData_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cse_kinect::PoseData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b0bc174e6016dc1293495107c6428485";
  }

  static const char* value(const  ::cse_kinect::PoseData_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb0bc174e6016dc12ULL;
  static const uint64_t static_value2 = 0x93495107c6428485ULL;
};

template<class ContainerAllocator>
struct DataType< ::cse_kinect::PoseData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cse_kinect/PoseData";
  }

  static const char* value(const  ::cse_kinect::PoseData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cse_kinect::PoseData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool mStop\n\
bool mGo\n\
bool mTooClose\n\
bool mTooFar\n\
bool mTooClockwise\n\
bool mTooCClockwise\n\
\n\
";
  }

  static const char* value(const  ::cse_kinect::PoseData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::cse_kinect::PoseData_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cse_kinect::PoseData_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.mStop);
    stream.next(m.mGo);
    stream.next(m.mTooClose);
    stream.next(m.mTooFar);
    stream.next(m.mTooClockwise);
    stream.next(m.mTooCClockwise);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PoseData_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cse_kinect::PoseData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cse_kinect::PoseData_<ContainerAllocator> & v) 
  {
    s << indent << "mStop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mStop);
    s << indent << "mGo: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mGo);
    s << indent << "mTooClose: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mTooClose);
    s << indent << "mTooFar: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mTooFar);
    s << indent << "mTooClockwise: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mTooClockwise);
    s << indent << "mTooCClockwise: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mTooCClockwise);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CSE_KINECT_MESSAGE_POSEDATA_H

